<?php

return [
    'cities' => [
        // Main Districts
        'purnea' => 'Purnea',
        'katihar' => 'Katihar',
        'araria' => 'Araria',
        'kishanganj' => 'Kishanganj',
        'bhagalpur' => 'Bhagalpur',
        'saharsa' => 'Saharsa',
        'madhepura' => 'Madhepura',
        'supaul' => 'Supaul',
        
        // Purnea Specific Localities (Hyper-Local SEO Expansion)
        'line-bazar-purnea' => 'Line Bazar, Purnea',
        'bhatta-bazar-purnea' => 'Bhatta Bazar, Purnea',
        'madhubani-purnea' => 'Madhubani, Purnea',
        'khazanchi-hat-purnea' => 'Khazanchi Hat, Purnea',
        'rambagh-purnea' => 'Rambagh, Purnea',
        'gulabbagh-purnea' => 'Gulabbagh, Purnea',
        'maranga-purnea' => 'Maranga, Purnea',
        'chunapur-purnea' => 'Chunapur, Purnea',
        'kasba-purnea' => 'Kasba, Purnea',
        'dagarua-purnea' => 'Dagarua, Purnea',
        'jalalgarh-purnea' => 'Jalalgarh, Purnea',
        'raniganj-purnea' => 'Raniganj, Purnea',
        'rupauli-purnea' => 'Rupauli, Purnea',
        'baisi-purnea' => 'Baisi, Purnea',
        'banmankhi-purnea' => 'Banmankhi, Purnea',
        'dhamdaha-purnea' => 'Dhamdaha, Purnea',
        'amandha-purnea' => 'Amandha, Purnea',
        'krityanand-nagar-purnea' => 'Krityanand Nagar, Purnea',
        'bhawanipur-purnea' => 'Bhawanipur, Purnea',
        'srinagar-purnea' => 'Srinagar, Purnea',
        'kali-mandir-chowk-purnea' => 'Kali Mandir Chowk, Purnea',
        'purnia-court-purnea' => 'Purnia Court, Purnea',
        'station-road-purnea' => 'Station Road, Purnea',
        'gulabbagh-road-purnea' => 'Gulabbagh Road, Purnea',
        'lakhimpur-purnea' => 'Lakhimpur, Purnea',
        'purani-basti-purnea' => 'Purani Basti, Purnea',
        'naya-tola-purnea' => 'Naya Tola, Purnea',
        'college-road-purnea' => 'College Road, Purnea',
        'hospital-road-purnea' => 'Hospital Road, Purnea',
        'rn-shaw-chowk-purnea' => 'RN Shaw Chowk, Purnea',
        'ford-company-purnea' => 'Ford Company, Purnea',
        'rajni-chowk-purnea' => 'Rajni Chowk, Purnea',
        'girja-chowk-purnea' => 'Girja Chowk, Purnea',
        'navratan-hat-purnea' => 'Navratan Hat, Purnea',
        'police-line-purnea' => 'Police Line, Purnea',
        'shastri-nagar-purnea' => 'Shastri Nagar, Purnea',
        'pratap-nagar-purnea' => 'Pratap Nagar, Purnea',
        'subhash-nagar-purnea' => 'Subhash Nagar, Purnea',
    ],
];
